### ISSUE TITLE
Get list for Threshold alerts and Alerts severity

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#191]
List to be based by base chain and saved in MongoDB.
Document the list for easy recall.

**Comment by itsciccio** [comment]
Created the following [spreadsheet](https://docs.google.com/spreadsheets/d/15Z3WqAJWGXe-mzhF9WIsDaEDSCasghvuBuSVL0C8zew/edit?usp=sharing):

It would be appreciated if anyone can review the sheets in the document which each comply with alerting metrics for Cosmos, Substrate and Chainlink. Kindly double-check that it complies with the data in the following:

`web-installer > src > redux > reducers > chainlinkChainsReducer.js &  cosmosChainsReducer & substrateChainsReducer`.

**Comment by zimaah** [comment]
Hey @itsciccio ! I just checked the document... what about `General` "base-chain"? Does it use the same as some other base-chain?

**Comment by zimaah** [comment]
I did the review for `Cosmos` alerts only. Find below what I spotted:
- "Missed block signatures" has a diff _critical_ threshold than what's currently here https://172.16.152.17:8000/ (`origin/develop` branch). 
- "System Storage alerted on based on percentage usage." I think we have an extra "on" in this sentence. It happens in diff alerts too.
- "The prometheus endpoint for a node has not been accessible for a some time." Remove the "a" from here "for a some time". In this sentence, we have also "prometheus" instead of "Prometheus".

I understand that you just copied & pasted whatever was there in the installer, but since we are working on gathering this information, I believe that we should do a full review, to not bring content with typos and whatnot to the new installer :wink: 

My suggestion:
- Upgrade the ticket's sp from 1 to 2
- Go over all alerts again, but now in more detail, to spot these typos and fix them. If you have any questions regarding a specific sentence, just drop a message in our channels, and we discuss as you go.
- We need to use capital letters and uppercase where applicable. Ex: Prometheus over prometheus, REST over rest, RPC over rpc, Tendermint over tendermint, etc.

What do you think, guys? Suggestions?

**Comment by itsciccio** [comment]
> Hey @itsciccio ! I just checked the document... what about `General` "base-chain"? Does it use the same as some other base-chain?

Ok, added just now.

> I did the review for `Cosmos` alerts only. Find below what I spotted:
> 
> * "Missed block signatures" has a diff _critical_ threshold than what's currently here https://172.16.152.17:8000/ (`origin/develop` branch).
> * "System Storage alerted on based on percentage usage." I think we have an extra "on" in this sentence. It happens in diff alerts too.
> * "The prometheus endpoint for a node has not been accessible for a some time." Remove the "a" from here "for a some time". In this sentence, we have also "prometheus" instead of "Prometheus".
> 
> I understand that you just copied & pasted whatever was there in the installer, but since we are working on gathering this information, I believe that we should do a full review, to not bring content with typos and whatnot to the new installer wink
> 
> My suggestion:
> 
> * Upgrade the ticket's sp from 1 to 2
> * Go over all alerts again, but now in more detail, to spot these typos and fix them. If you have any questions regarding a specific sentence, just drop a message in our channels, and we discuss as you go.
> * We need to use capital letters and uppercase where applicable. Ex: Prometheus over prometheus, REST over rest, RPC over rpc, Tendermint over tendermint, etc.
> 
> What do you think, guys? Suggestions?

Fixed all typos and capitalization. Also went over the metrics to make sure they match with those in the installer `develop` branch.
