### ISSUE TITLE
UI: Application reloads when navigating from one page to another

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#321]
### Summary of bug
Navigation using window.location.href causes the whole app to reload, breaking the UX by quickly showing a blank page between the beginning and the end of the navigation.
See [PANIC-UI-Nav-Glitch.webm](https://user-images.githubusercontent.com/89395527/179492537-67103ecc-1370-4a7a-9e94-9a5049fee879.webm)

Notes:
- We need to use the method provided by the router lib.
- Our current router lib is deprecated, we need to update to this https://github.com/stencil-community/stencil-router and follow the docs to implement programmable navigation (navigation via JS).
- All routes must be updated to ensure that the whole app remains intact.

### 'As is' behaviour 

When navigating through the UI (for example, when clicking on the PANIC home button in the header to go to home, and when clicking on the edit icon from Settings -> Channels table) we briefly display a blank screen before the user is taken to the correct page.

### 'To be' behaviour

Navigation through the UI is clean, without the display of a blank screen.

### Steps to reproduce

Although this behaviour is present across a range of navigation components, this can be reporduced by clicking on the Settings dropdown in the header and choosing Channels.

### Acceptance criteria

**Given**: The user is on the UI
**When**: He selects to navigate through the UI
**Then**: Navigation through the UI is clean, without the display of a blank screen

**Comment by crsfalzon** [comment]
Investigate if a Stencil upgrade needs to be done.

**Comment by Cherrett** [comment]
Investigation outcome:

- For PANIC UI, we are currently using `stencil-router-v2` version `0.6.0`. [This package](https://github.com/ionic-team/stencil-router-v2) was an experimental router by the ionic/stencil team but this never reached v1.0 status (production). Moreover, this package will be archived soon but as noted on their GitHub, their latest version can still be used via npm.
- `@stencil/router` was updated to `@stencil-community/router` in latest version (`1.0.2`). [This package](https://github.com/stencil-community/stencil-router) is the default stencil router and a part of this investigation was to switch to it.
- The issue with the `@stencil-community/router` package is that it looks like it only supports version 1 of stencil. This was also highlighted by other people in one of the issues, as can be seen [here](https://github.com/stencil-community/stencil-router/issues/131). I am getting the same error as seen in this issue when building PANIC UI with this router.
- I tried to force the use of this package but from what I tried, I do not think that it is possible. This is possibly why we opted for the new router when starting PANIC UI. 
- For the above, I tried lowering the typescript version so that the `@stencil-community/router` package builds successfully. With Typescript 3, there were no dependency conflicts but the router was still erroring when building. When switching to Typescript 2.9.2, I get a dependency error when running `npm install`. This was fixed by downgrading the following packages: `ts-jest`, `jest`, `@types/jest`. The issue is that this typescript version breaks the `@stencil/core` option so it is not feasible. Moreover, it created a lot of vulnerabilities (35 vulnerabilities (13 low, 16 moderate, 6 high).
- So as a summary, based on the points mentioned above, I believe that it is not feasible to switch to the old router (`@stencil-community/router`). Moreover, the current router we are using (`stencil-router-v2`) will still work in the long-run. It was also noted that the issue in the original ticket (application reloads when navigating from one page to another) was not occurring on all platforms running PANIC UI (me and Ciccio could not replicate this).
