### ISSUE TITLE
Fix failing UI tests

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#326]
### User Story

As a node operator I want to be certain that the code that I am running is well tested. Therefore all written tests must pass.

### Requirements

See #316. Implement removal/fixing of test.

### Blocked by

#316

### Acceptance criteria

Scenario: Situation of use case
Given: I run the UI test suite
Then: All tests pass

**Comment by dillu24** [comment]
All tests now pass. The following fixes were done:

1. Tests which required a lot of effort to be fixed and which bring little to no value were removed.
2. Tests that cannot be fixed for the time being because we need to integrate with the API were removed or modified slightly for the time being. The reason being is that these tests still need to be re-written, so for the time being they are not needed and/or their scope should not be expanded.
3. For unstable screenshot tests we are now using `SpecPage` and not `E2EPage` which looks to be more stable.
4. Changes in mocked variables.
