### ISSUE TITLE
Investigation - Alert user when he is about to lose data (installer)

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#332]
### Rationale

The current version of the installer informs the node operator when he is navigating away from a form without saving his changes. We need to understand the effort involved in this feature, and if there's a workaround available.

### For ticket closure

Understand the working effort required to duplicate the feature in the current installer. Then a decision will be made on how to proceed. See #300

**Comment by dillu24** [comment]
After performing the investigation we concluded the following:

1. Having a modal each time popping up whenever the user is about to navigate away from a page is no longer required because we no longer have forms embedded on a page, but forms embedded on a pop-up. Therefore, the user can't navigate away from a form unless they click cancel .. in which case it is understandable that the data is lost.
2. There is only 2 forms embedded directly with a navigation, the subchain page of the installer and the alerts page of the installer. In case of the subchain page, you only loose the data whenever you click back, in which case this is not a big deal as you only need to enter the subchain name. In the case of the alerts page what we can do is create an `isModified` boolean field which by default is set to false in the form such that whenever one of the entries is modified, `isModifed` is set to true. If `isModified` is set to true a pop up is shown on `back` asking the user if they want to save before proceeding further.
3. Another thing worth fixing is to disable every modal from being closed whenever the user clicks outside of the modal. Like this we can prevent the user from loosing data if they accidently click outside of the modal. See https://forum.ionicframework.com/t/ionic-dismiss-modal-when-click-outside-of-element/172762/2
