### ISSUE TITLE
Release candidate for DockerHub monitoring and UI iteration 1

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#67]
Prepare release candidate for testing by staking + update documentation

**Comment by dillu24** [comment]
When tackling this issue we need to perform the following:

**Documentation**:
1. Read and update the existing README.md so that it includes mentioning dockerhub and the UI
2. Read and update the UI documentation to confirm that it is up to date
3. Include DockerHub monitoring in the Design_and_features.md alerting section and architecture design image. It is best to read the entire docs to make sure that it still makes sense.

**Deploy**:

When the above is ready we should ask the staking team for a vm so that we run a release candidate for them to review.

**Comment by Cherrett** [comment]
We also need to make sure to update PANIC UI to be in-line with the latest UI Kit version since there will be breaking changes with the new release.

**Comment by dillu24** [comment]
@Cherrett Another thing we need to check is the API and UI security vulnerabilities which can be solved via `npm audit fix`.
